{% set version = "1.0.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-googlesheets4
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/googlesheets4_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/googlesheets4/googlesheets4_{{ version }}.tar.gz
  sha256: 284ecbce98944093cb065c1b0b32074eae7b45fd74b87d7815c7ca6deca76591

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cellranger
    - r-cli >=3.0.0
    - r-curl
    - r-gargle >=1.2.0
    - r-glue >=1.3.0
    - r-googledrive >=2.0.0
    - r-httr
    - r-ids
    - r-magrittr
    - r-purrr
    - r-rematch2
    - r-rlang >=0.4.11
    - r-tibble >=2.1.1
    - r-vctrs >=0.2.3
  run:
    - r-base
    - r-cellranger
    - r-cli >=3.0.0
    - r-curl
    - r-gargle >=1.2.0
    - r-glue >=1.3.0
    - r-googledrive >=2.0.0
    - r-httr
    - r-ids
    - r-magrittr
    - r-purrr
    - r-rematch2
    - r-rlang >=0.4.11
    - r-tibble >=2.1.1
    - r-vctrs >=0.2.3

test:
  commands:
    - $R -e "library('googlesheets4')"           # [not win]
    - "\"%R%\" -e \"library('googlesheets4')\""  # [win]

about:
  home: https://googlesheets4.tidyverse.org, https://github.com/tidyverse/googlesheets4
  license: MIT
  summary: Interact with Google Sheets through the Sheets API v4 <https://developers.google.com/sheets/api>. "API" is an acronym for "application programming interface"; the Sheets API allows users to interact with Google Sheets programmatically, instead of via a web browser. The "v4" refers to the fact that the Sheets API
    is currently at version 4. This package can read and write both the metadata and the cell data in a Sheet.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: googlesheets4
# Title: Access Google Sheets using the Sheets API V4
# Version: 1.0.0
# Authors@R: c(person(given = "Jennifer", family = "Bryan", role = c("cre", "aut"), email = "jenny@rstudio.com", comment = c(ORCID = "0000-0002-6983-2759")), person(given = "RStudio", role = c("cph", "fnd")))
# Description: Interact with Google Sheets through the Sheets API v4 <https://developers.google.com/sheets/api>. "API" is an acronym for "application programming interface"; the Sheets API allows users to interact with Google Sheets programmatically, instead of via a web browser. The "v4" refers to the fact that the Sheets API is currently at version 4. This package can read and write both the metadata and the cell data in a Sheet.
# License: MIT + file LICENSE
# URL: https://googlesheets4.tidyverse.org, https://github.com/tidyverse/googlesheets4
# BugReports: https://github.com/tidyverse/googlesheets4/issues
# Depends: R (>= 3.3)
# Imports: cellranger, cli (>= 3.0.0), curl, gargle (>= 1.2.0), glue (>= 1.3.0), googledrive (>= 2.0.0), httr, ids, magrittr, methods, purrr, rematch2, rlang (>= 0.4.11), tibble (>= 2.1.1), utils, vctrs (>= 0.2.3)
# Suggests: covr, readr, rmarkdown, sodium, spelling, testthat (>= 3.0.0), withr
# ByteCompile: true
# Config/Needs/website: pkgdown, tidyverse, r-lib/downlit, tidyverse/tidytemplate
# Config/testthat/edition: 3
# Encoding: UTF-8
# Language: en-US
# RoxygenNote: 7.1.1.9001
# NeedsCompilation: no
# Packaged: 2021-07-21 18:20:53 UTC; jenny
# Author: Jennifer Bryan [cre, aut] (<https://orcid.org/0000-0002-6983-2759>), RStudio [cph, fnd]
# Maintainer: Jennifer Bryan <jenny@rstudio.com>
# Repository: CRAN
# Date/Publication: 2021-07-21 18:50:01 UTC
